[tool.pytest.ini_options]
addopts = "--verbose --color=yes --random-order --cov --cov-report html --cov-config=setup.pyproject.toml"
testpaths = ["tests",]
filterwarnings = [
    "ignore:Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since python 3.3,and in 3.9 it will stop working",
    "ignore:the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses",
]

