environment              = "development"
aws_region               = "us-east-2"
tfstate_bucket           = "vcprototypes-dev-terraform-state"
tfstate_bucket_region    = "us-east-2"
serverless_deploy_bucket = "vcprototypes-dev-serverless"
project_name             = "python-cognito"
stage_name               = "development"
